language: node_js
node_js: node
sudo: false
cache:
  directories:
    - node_modules
branches:
  only:
  - feature/semver
before_deploy:
  - npx semantic-release
deploy:
  provider: npm
  email: "$EMAIL"
  api_key:
    secure: "$NPM_API_KEY"
  on:
    tags: true
    repo: SoftboxLab/gandalf-lint


language: node_js

node_js:
  - 8
  - 6

jobs:
  include:
    - stage: release
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
